from abc import ABC, abstractmethod
from sentinel.models import CommandResult, PatchResult


class Runtime(ABC):
    @abstractmethod
    async def start(self) -> CommandResult: ...
    @abstractmethod
    async def stop(self) -> CommandResult: ...
    @abstractmethod
    async def restart(self) -> CommandResult: ...
    @abstractmethod
    async def exec(self, cmd: str, timeout: int = 30) -> CommandResult: ...
    @abstractmethod
    async def apply_patch(self, file_path: str, diff_text: str) -> PatchResult: ...
